name: 음극재 뉴스 텔레그램 봇

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3
      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: 필요한 패키지 설치
        run: pip install requests beautifulsoup4
      - name: 뉴스 봇 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python news_bot.py
